//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "entities_versioned_contents")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version: String,
    pub entity_id: i32,
    pub versioned_content_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::entities::Entity",
        from = "Column::EntityId",
        to = "super::entities::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Entities,
    #[sea_orm(
        belongs_to = "super::versioned_contents::Entity",
        from = "Column::VersionedContentId",
        to = "super::versioned_contents::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    VersionedContents,
}

impl Related<super::entities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Entities.def()
    }
}

impl Related<super::versioned_contents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VersionedContents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::entities::Entity")]
    Entities,
    #[sea_orm(entity = "super::versioned_contents::Entity")]
    VersionedContents,
}
