//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod entities;
pub mod entities_versioned_contents;
pub mod users;
pub mod versioned_contents;

seaography::register_entity_modules!([
    entities,
    entities_versioned_contents,
    users,
    versioned_contents,
]);
