//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::entities::Entity as Entities;
pub use super::entities_versioned_contents::Entity as EntitiesVersionedContents;
pub use super::users::Entity as Users;
pub use super::versioned_contents::Entity as VersionedContents;
